# https://docs.gitea.com/administration/config-cheat-sheet
APP_NAME = Gitea: Git with a cup of tea
RUN_MODE = prod
RUN_USER = git

[repository]
ROOT = /data/git/repositories

[server]
SSH_DOMAIN       = localhost
HTTP_PORT        = 3000
ROOT_URL         = http://0.0.0.0:3000/
DISABLE_SSH      = false
SSH_PORT         = 2222
LFS_START_SERVER = true

[database]
DB_TYPE  = sqlite3
PATH     = /data/gitea/gitea.db

# [security]
# INSTALL_LOCK = true

[openid]
ENABLE_OPENID_SIGNIN = false
ENABLE_OPENID_SIGNUP = false

[service]
DISABLE_REGISTRATION = false
REQUIRE_SIGNIN_VIEW  = false